[tool.poetry]
name = "flet-demo"
version = "0.1.0"
description = ""
authors = ["Yoshihiro Tanaka <contact@cordea.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
